// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dtuqcajqwkcdcnvsewlr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR0dXFjYWpxd2tjZGNudnNld2xyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIyMTYyMTQsImV4cCI6MjA2Nzc5MjIxNH0.y9ZKUDjmiPFGa5XjSQA_7IM2JZNQv2tMU9brsHgA2e8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});